import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from pathlib import Path

from mcsr.tree.grammar import Grammar
from mcsr.utils.predictor import PredictorNN

class DummySymbolicDataset(Dataset):
    """
    A dummy dataset to simulate trajectories generated by MCTS/PUCT.
    In a real scenario, this would load actual search trajectories.
    """
    def __init__(self, grammar: Grammar, num_samples: int = 1000, max_seq_len: int = 10):
        self.grammar = grammar
        self.num_samples = num_samples
        self.max_seq_len = max_seq_len
        self.vocab_size = len(grammar.all_atoms)
        
    def __len__(self) -> int:
        return self.num_samples
        
    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        import random
        seq_len = random.randint(1, self.max_seq_len)
        
        # Random sequence of token indices
        seq = torch.randint(0, self.vocab_size, (seq_len,))
        
        # Random value in [-1, 1]
        value_target = torch.rand(1) * 2 - 1
        
        # Random policy target (probabilities)
        policy_target = torch.rand(self.vocab_size)
        policy_target = policy_target / policy_target.sum()
        
        return seq, value_target, policy_target


def collate_fn(batch):
    sequences, values, policies = zip(*batch)
    lengths = torch.tensor([len(seq) for seq in sequences])
    
    # Pad sequences with the padding index (vocab_size)
    # The padding index is expected to be vocab_size as per our embedding layer
    # But since all atoms are 0 to vocab_size-1, padding is vocab_size
    padding_value = sequences[0].new_tensor([0]) # we will replace 0 with proper padding later
    # Actually we can just use 0 here, or grab the vocab_size from the model, but 
    # nn.utils.rnn.pad_sequence handles this.
    padded_seqs = nn.utils.rnn.pad_sequence(sequences, batch_first=True, padding_value=0)
    
    values = torch.stack(values)
    policies = torch.stack(policies)
    
    return padded_seqs, lengths, values, policies


def train():
    print("Initializing Grammar and Predictor...")
    grammar = Grammar(num_variables=2)
    model = PredictorNN(grammar=grammar)
    
    dataset = DummySymbolicDataset(grammar)
    dataloader = DataLoader(dataset, batch_size=32, shuffle=True, collate_fn=collate_fn)
    
    optimizer = optim.Adam(model.parameters(), lr=1e-3)
    value_criterion = nn.MSELoss()
    
    # For predicting a probability distribution, CrossEntropyLoss expects class indices if target is 1D,
    # or probabilities if target is same shape as input (since PyTorch 1.10).
    policy_criterion = nn.CrossEntropyLoss()
    
    checkpoint_dir = Path("checkpoints")
    checkpoint_dir.mkdir(exist_ok=True)
    
    epochs = 2
    print("Starting training loop...")
    for epoch in range(epochs):
        model.train()
        total_loss = 0.0
        
        for batch_idx, (seqs, lengths, values, policies) in enumerate(dataloader):
            optimizer.zero_grad()
            
            # Predict
            pred_values, pred_policies = model(seqs, lengths)
            
            # Values Loss
            loss_v = value_criterion(pred_values, values.squeeze(1))
            
            # Policy Loss
            loss_p = policy_criterion(pred_policies, policies)
            
            # Total Loss
            loss = loss_v + loss_p
            loss.backward()
            optimizer.step()
            
            total_loss += loss.item()
            
        avg_loss = total_loss / len(dataloader)
        print(f"Epoch {epoch+1}/{epochs} | Loss: {avg_loss:.4f}")
        
        # Save checkpoint
        checkpoint_path = checkpoint_dir / f"predictor_epoch_{epoch+1}.pt"
        torch.save(model.state_dict(), checkpoint_path)
        print(f" -> Checkpoint saved to {checkpoint_path}")

    print("Training finished.")


if __name__ == "__main__":
    train()
